"""Add song notes column

Revision ID: 0721a0c51f30
Revises: b027ba75dc98
Create Date: 2023-09-10 16:34:15.932071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0721a0c51f30'
down_revision: Union[str, None] = 'b027ba75dc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'notes')
    # ### end Alembic commands ###
