"""Added songs table

Revision ID: 7ba449630fd5
Revises: 
Create Date: 2023-09-02 15:06:25.486172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba449630fd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_path'), 'songs', ['path'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_table('songlyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lyrics', sa.String(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songlyrics_id'), 'songlyrics', ['id'], unique=False)
    op.create_index(op.f('ix_songlyrics_language'), 'songlyrics', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songlyrics_language'), table_name='songlyrics')
    op.drop_index(op.f('ix_songlyrics_id'), table_name='songlyrics')
    op.drop_table('songlyrics')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_path'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
