"""Added songs subsonic id column

Revision ID: b027ba75dc98
Revises: 7ba449630fd5
Create Date: 2023-09-02 18:16:34.970372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b027ba75dc98'
down_revision: Union[str, None] = '7ba449630fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column(
        'subsonic_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'subsonic_id')
    # ### end Alembic commands ###
